/* lib/timezones.ts — curated IANA timezone list for the timezone picker */

export interface TimezoneOption {
  value: string
  label: string
}

export const TIMEZONES: TimezoneOption[] = [
  // Universal
  { value: "UTC",                              label: "UTC — Coordinated Universal Time" },
  { value: "GMT",                              label: "GMT — Greenwich Mean Time" },

  // Americas — US
  { value: "America/New_York",                 label: "America/New_York — Eastern Time (ET)" },
  { value: "America/Detroit",                  label: "America/Detroit — Eastern Time" },
  { value: "America/Indiana/Indianapolis",     label: "America/Indiana/Indianapolis — Eastern Time" },
  { value: "America/Indiana/Knox",             label: "America/Indiana/Knox — Central Time" },
  { value: "America/Chicago",                  label: "America/Chicago — Central Time (CT)" },
  { value: "America/Denver",                   label: "America/Denver — Mountain Time (MT)" },
  { value: "America/Boise",                    label: "America/Boise — Mountain Time" },
  { value: "America/Phoenix",                  label: "America/Phoenix — Mountain Standard Time (no DST)" },
  { value: "America/Los_Angeles",              label: "America/Los_Angeles — Pacific Time (PT)" },
  { value: "America/Anchorage",                label: "America/Anchorage — Alaska Time (AKT)" },
  { value: "America/Adak",                     label: "America/Adak — Hawaii-Aleutian Time" },
  { value: "Pacific/Honolulu",                 label: "Pacific/Honolulu — Hawaii Standard Time (HST)" },
  { value: "America/Kentucky/Louisville",      label: "America/Kentucky/Louisville — Eastern Time" },
  { value: "America/North_Dakota/Center",      label: "America/North_Dakota/Center — Central Time" },

  // Americas — Canada
  { value: "America/Toronto",                  label: "America/Toronto — Eastern Time (Canada)" },
  { value: "America/Winnipeg",                 label: "America/Winnipeg — Central Time (Canada)" },
  { value: "America/Regina",                   label: "America/Regina — Central Standard Time (Canada, no DST)" },
  { value: "America/Edmonton",                 label: "America/Edmonton — Mountain Time (Canada)" },
  { value: "America/Vancouver",                label: "America/Vancouver — Pacific Time (Canada)" },
  { value: "America/Halifax",                  label: "America/Halifax — Atlantic Time (Canada)" },
  { value: "America/St_Johns",                 label: "America/St_Johns — Newfoundland Time (UTC-3:30)" },
  { value: "America/Whitehorse",               label: "America/Whitehorse — Yukon Time" },
  { value: "America/Yellowknife",              label: "America/Yellowknife — Mountain Time (NWT)" },

  // Americas — Mexico
  { value: "America/Mexico_City",              label: "America/Mexico_City — Central Time (Mexico)" },
  { value: "America/Monterrey",                label: "America/Monterrey — Central Time (Mexico)" },
  { value: "America/Tijuana",                  label: "America/Tijuana — Pacific Time (Mexico)" },
  { value: "America/Cancun",                   label: "America/Cancun — Eastern Standard Time (Mexico, no DST)" },
  { value: "America/Hermosillo",               label: "America/Hermosillo — Mountain Standard Time (Mexico, no DST)" },
  { value: "America/Chihuahua",                label: "America/Chihuahua — Mountain Time (Mexico)" },
  { value: "America/Mazatlan",                 label: "America/Mazatlan — Mountain Time (Mexico)" },

  // Americas — Central America & Caribbean
  { value: "America/Guatemala",                label: "America/Guatemala — Central Standard Time" },
  { value: "America/Belize",                   label: "America/Belize — Central Standard Time" },
  { value: "America/El_Salvador",              label: "America/El_Salvador — Central Standard Time" },
  { value: "America/Tegucigalpa",              label: "America/Tegucigalpa — Central Standard Time" },
  { value: "America/Managua",                  label: "America/Managua — Central Standard Time" },
  { value: "America/Costa_Rica",               label: "America/Costa_Rica — Central Standard Time" },
  { value: "America/Panama",                   label: "America/Panama — Eastern Standard Time" },
  { value: "America/Havana",                   label: "America/Havana — Cuba Standard Time" },
  { value: "America/Jamaica",                  label: "America/Jamaica — Eastern Standard Time (no DST)" },
  { value: "America/Puerto_Rico",              label: "America/Puerto_Rico — Atlantic Standard Time" },
  { value: "America/Santo_Domingo",            label: "America/Santo_Domingo — Atlantic Standard Time" },
  { value: "America/Port-au-Prince",           label: "America/Port-au-Prince — Eastern Time" },
  { value: "America/Nassau",                   label: "America/Nassau — Eastern Time (Bahamas)" },
  { value: "America/Grand_Turk",               label: "America/Grand_Turk — Eastern Time" },
  { value: "America/Barbados",                 label: "America/Barbados — Atlantic Standard Time" },
  { value: "America/Trinidad",                 label: "America/Trinidad — Atlantic Standard Time" },
  { value: "America/Curacao",                  label: "America/Curacao — Atlantic Standard Time" },

  // Americas — South America
  { value: "America/Bogota",                   label: "America/Bogota — Colombia Time (UTC-5)" },
  { value: "America/Lima",                     label: "America/Lima — Peru Time (UTC-5)" },
  { value: "America/Guayaquil",                label: "America/Guayaquil — Ecuador Time (UTC-5)" },
  { value: "America/Caracas",                  label: "America/Caracas — Venezuela Time (UTC-4)" },
  { value: "America/La_Paz",                   label: "America/La_Paz — Bolivia Time (UTC-4)" },
  { value: "America/Manaus",                   label: "America/Manaus — Amazon Time (UTC-4)" },
  { value: "America/Cuiaba",                   label: "America/Cuiaba — Amazon Time" },
  { value: "America/Santiago",                 label: "America/Santiago — Chile Time" },
  { value: "America/Asuncion",                 label: "America/Asuncion — Paraguay Time" },
  { value: "America/Argentina/Buenos_Aires",   label: "America/Argentina/Buenos_Aires — Argentina Time (UTC-3)" },
  { value: "America/Montevideo",               label: "America/Montevideo — Uruguay Time (UTC-3)" },
  { value: "America/Sao_Paulo",                label: "America/Sao_Paulo — Brasilia Time (UTC-3)" },
  { value: "America/Fortaleza",                label: "America/Fortaleza — Brasilia Time (no DST)" },
  { value: "America/Recife",                   label: "America/Recife — Brasilia Time (no DST)" },
  { value: "America/Belem",                    label: "America/Belem — Brasilia Time" },
  { value: "America/Cayenne",                  label: "America/Cayenne — French Guiana Time (UTC-3)" },
  { value: "America/Paramaribo",               label: "America/Paramaribo — Suriname Time (UTC-3)" },
  { value: "America/Guyana",                   label: "America/Guyana — Guyana Time (UTC-4)" },
  { value: "Atlantic/South_Georgia",           label: "Atlantic/South_Georgia — South Georgia Time (UTC-2)" },
  { value: "America/Noronha",                  label: "America/Noronha — Fernando de Noronha Time (UTC-2)" },

  // Europe — Western
  { value: "Europe/London",                    label: "Europe/London — Greenwich / British Time (GMT/BST)" },
  { value: "Europe/Dublin",                    label: "Europe/Dublin — Irish Standard Time (IST)" },
  { value: "Europe/Lisbon",                    label: "Europe/Lisbon — Western European Time (WET/WEST)" },
  { value: "Atlantic/Azores",                  label: "Atlantic/Azores — Azores Time (UTC-1/0)" },
  { value: "Atlantic/Canary",                  label: "Atlantic/Canary — Western European Time" },
  { value: "Atlantic/Madeira",                 label: "Atlantic/Madeira — Western European Time" },
  { value: "Atlantic/Reykjavik",               label: "Atlantic/Reykjavik — Greenwich Mean Time (Iceland)" },

  // Europe — Central
  { value: "Europe/Paris",                     label: "Europe/Paris — Central European Time (CET/CEST)" },
  { value: "Europe/Berlin",                    label: "Europe/Berlin — Central European Time (CET/CEST)" },
  { value: "Europe/Madrid",                    label: "Europe/Madrid — Central European Time (CET/CEST)" },
  { value: "Europe/Rome",                      label: "Europe/Rome — Central European Time (CET/CEST)" },
  { value: "Europe/Amsterdam",                 label: "Europe/Amsterdam — Central European Time (CET/CEST)" },
  { value: "Europe/Brussels",                  label: "Europe/Brussels — Central European Time (CET/CEST)" },
  { value: "Europe/Vienna",                    label: "Europe/Vienna — Central European Time (CET/CEST)" },
  { value: "Europe/Zurich",                    label: "Europe/Zurich — Central European Time (CET/CEST)" },
  { value: "Europe/Luxembourg",                label: "Europe/Luxembourg — Central European Time (CET/CEST)" },
  { value: "Europe/Monaco",                    label: "Europe/Monaco — Central European Time (CET/CEST)" },
  { value: "Europe/Warsaw",                    label: "Europe/Warsaw — Central European Time (CET/CEST)" },
  { value: "Europe/Prague",                    label: "Europe/Prague — Central European Time (CET/CEST)" },
  { value: "Europe/Budapest",                  label: "Europe/Budapest — Central European Time (CET/CEST)" },
  { value: "Europe/Zagreb",                    label: "Europe/Zagreb — Central European Time (CET/CEST)" },
  { value: "Europe/Belgrade",                  label: "Europe/Belgrade — Central European Time (CET/CEST)" },
  { value: "Europe/Bratislava",                label: "Europe/Bratislava — Central European Time (CET/CEST)" },
  { value: "Europe/Ljubljana",                 label: "Europe/Ljubljana — Central European Time (CET/CEST)" },
  { value: "Europe/Sarajevo",                  label: "Europe/Sarajevo — Central European Time (CET/CEST)" },
  { value: "Europe/Skopje",                    label: "Europe/Skopje — Central European Time (CET/CEST)" },
  { value: "Europe/Tirane",                    label: "Europe/Tirane — Central European Time (CET/CEST)" },
  { value: "Europe/Stockholm",                 label: "Europe/Stockholm — Central European Time (CET/CEST)" },
  { value: "Europe/Copenhagen",                label: "Europe/Copenhagen — Central European Time (CET/CEST)" },
  { value: "Europe/Oslo",                      label: "Europe/Oslo — Central European Time (CET/CEST)" },
  { value: "Europe/Malta",                     label: "Europe/Malta — Central European Time (CET/CEST)" },
  { value: "Europe/Andorra",                   label: "Europe/Andorra — Central European Time (CET/CEST)" },

  // Europe — Eastern
  { value: "Europe/Helsinki",                  label: "Europe/Helsinki — Eastern European Time (EET/EEST)" },
  { value: "Europe/Riga",                      label: "Europe/Riga — Eastern European Time (EET/EEST)" },
  { value: "Europe/Tallinn",                   label: "Europe/Tallinn — Eastern European Time (EET/EEST)" },
  { value: "Europe/Vilnius",                   label: "Europe/Vilnius — Eastern European Time (EET/EEST)" },
  { value: "Europe/Bucharest",                 label: "Europe/Bucharest — Eastern European Time (EET/EEST)" },
  { value: "Europe/Sofia",                     label: "Europe/Sofia — Eastern European Time (EET/EEST)" },
  { value: "Europe/Athens",                    label: "Europe/Athens — Eastern European Time (EET/EEST)" },
  { value: "Europe/Nicosia",                   label: "Europe/Nicosia — Eastern European Time (EET/EEST)" },
  { value: "Europe/Kiev",                      label: "Europe/Kiev — Eastern European Time (EET/EEST)" },
  { value: "Europe/Chisinau",                  label: "Europe/Chisinau — Eastern European Time (EET/EEST)" },
  { value: "Europe/Kaliningrad",               label: "Europe/Kaliningrad — Eastern European Time (UTC+2, no DST)" },
  { value: "Europe/Istanbul",                  label: "Europe/Istanbul — Turkey Time (TRT, UTC+3)" },
  { value: "Europe/Minsk",                     label: "Europe/Minsk — Moscow Standard Time (UTC+3, no DST)" },
  { value: "Europe/Moscow",                    label: "Europe/Moscow — Moscow Standard Time (MSK, UTC+3)" },
  { value: "Europe/Samara",                    label: "Europe/Samara — Samara Time (UTC+4)" },
  { value: "Europe/Ulyanovsk",                 label: "Europe/Ulyanovsk — Ulyanovsk Time (UTC+4)" },

  // Africa
  { value: "Africa/Casablanca",                label: "Africa/Casablanca — Western European Time (UTC+1)" },
  { value: "Africa/Algiers",                   label: "Africa/Algiers — Central European Time (UTC+1, no DST)" },
  { value: "Africa/Tunis",                     label: "Africa/Tunis — Central European Time (UTC+1)" },
  { value: "Africa/Tripoli",                   label: "Africa/Tripoli — Eastern European Time (UTC+2, no DST)" },
  { value: "Africa/Cairo",                     label: "Africa/Cairo — Eastern European Time (UTC+2, no DST)" },
  { value: "Africa/Ceuta",                     label: "Africa/Ceuta — Central European Time (CET/CEST)" },
  { value: "Africa/Accra",                     label: "Africa/Accra — Greenwich Mean Time (UTC+0)" },
  { value: "Africa/Abidjan",                   label: "Africa/Abidjan — Greenwich Mean Time (UTC+0)" },
  { value: "Africa/Lagos",                     label: "Africa/Lagos — West Africa Time (WAT, UTC+1)" },
  { value: "Africa/Kinshasa",                  label: "Africa/Kinshasa — West Africa Time (WAT, UTC+1)" },
  { value: "Africa/Luanda",                    label: "Africa/Luanda — West Africa Time (WAT, UTC+1)" },
  { value: "Africa/Ndjamena",                  label: "Africa/Ndjamena — West Africa Time (WAT, UTC+1)" },
  { value: "Africa/Khartoum",                  label: "Africa/Khartoum — Central Africa Time (CAT, UTC+2)" },
  { value: "Africa/Maputo",                    label: "Africa/Maputo — Central Africa Time (CAT, UTC+2)" },
  { value: "Africa/Harare",                    label: "Africa/Harare — Central Africa Time (CAT, UTC+2)" },
  { value: "Africa/Lusaka",                    label: "Africa/Lusaka — Central Africa Time (CAT, UTC+2)" },
  { value: "Africa/Johannesburg",              label: "Africa/Johannesburg — South Africa Standard Time (SAST, UTC+2)" },
  { value: "Africa/Nairobi",                   label: "Africa/Nairobi — East Africa Time (EAT, UTC+3)" },
  { value: "Africa/Addis_Ababa",               label: "Africa/Addis_Ababa — East Africa Time (EAT, UTC+3)" },
  { value: "Africa/Dar_es_Salaam",             label: "Africa/Dar_es_Salaam — East Africa Time (EAT, UTC+3)" },
  { value: "Africa/Kampala",                   label: "Africa/Kampala — East Africa Time (EAT, UTC+3)" },

  // Middle East
  { value: "Asia/Jerusalem",                   label: "Asia/Jerusalem — Israel Standard Time (IST, UTC+2/3)" },
  { value: "Asia/Beirut",                      label: "Asia/Beirut — Eastern European Time (EET/EEST)" },
  { value: "Asia/Amman",                       label: "Asia/Amman — Eastern European Time (EET/EEST)" },
  { value: "Asia/Damascus",                    label: "Asia/Damascus — Eastern European Time (EET/EEST)" },
  { value: "Asia/Gaza",                        label: "Asia/Gaza — Eastern European Time (EET/EEST)" },
  { value: "Asia/Baghdad",                     label: "Asia/Baghdad — Arabia Standard Time (AST, UTC+3)" },
  { value: "Asia/Riyadh",                      label: "Asia/Riyadh — Arabia Standard Time (AST, UTC+3)" },
  { value: "Asia/Kuwait",                      label: "Asia/Kuwait — Arabia Standard Time (AST, UTC+3)" },
  { value: "Asia/Qatar",                       label: "Asia/Qatar — Arabia Standard Time (AST, UTC+3)" },
  { value: "Asia/Bahrain",                     label: "Asia/Bahrain — Arabia Standard Time (AST, UTC+3)" },
  { value: "Asia/Aden",                        label: "Asia/Aden — Arabia Standard Time (AST, UTC+3)" },
  { value: "Asia/Tehran",                      label: "Asia/Tehran — Iran Standard Time (IRST, UTC+3:30)" },
  { value: "Asia/Dubai",                       label: "Asia/Dubai — Gulf Standard Time (GST, UTC+4)" },
  { value: "Asia/Muscat",                      label: "Asia/Muscat — Gulf Standard Time (GST, UTC+4)" },
  { value: "Asia/Baku",                        label: "Asia/Baku — Azerbaijan Time (AZT, UTC+4)" },
  { value: "Asia/Tbilisi",                     label: "Asia/Tbilisi — Georgia Standard Time (GET, UTC+4)" },
  { value: "Asia/Yerevan",                     label: "Asia/Yerevan — Armenia Time (AMT, UTC+4)" },
  { value: "Asia/Kabul",                       label: "Asia/Kabul — Afghanistan Time (AFT, UTC+4:30)" },

  // Asia — Central & South
  { value: "Asia/Karachi",                     label: "Asia/Karachi — Pakistan Standard Time (PKT, UTC+5)" },
  { value: "Asia/Tashkent",                    label: "Asia/Tashkent — Uzbekistan Time (UZT, UTC+5)" },
  { value: "Asia/Ashgabat",                    label: "Asia/Ashgabat — Turkmenistan Time (TMT, UTC+5)" },
  { value: "Asia/Dushanbe",                    label: "Asia/Dushanbe — Tajikistan Time (TJT, UTC+5)" },
  { value: "Asia/Yekaterinburg",               label: "Asia/Yekaterinburg — Yekaterinburg Time (YEKT, UTC+5)" },
  { value: "Asia/Kolkata",                     label: "Asia/Kolkata — India Standard Time (IST, UTC+5:30)" },
  { value: "Asia/Colombo",                     label: "Asia/Colombo — Sri Lanka Time (SLST, UTC+5:30)" },
  { value: "Asia/Kathmandu",                   label: "Asia/Kathmandu — Nepal Time (NPT, UTC+5:45)" },
  { value: "Asia/Dhaka",                       label: "Asia/Dhaka — Bangladesh Standard Time (BST, UTC+6)" },
  { value: "Asia/Almaty",                      label: "Asia/Almaty — Alma-Ata Time (ALMT, UTC+6)" },
  { value: "Asia/Bishkek",                     label: "Asia/Bishkek — Kyrgyzstan Time (KGT, UTC+6)" },
  { value: "Asia/Omsk",                        label: "Asia/Omsk — Omsk Time (OMST, UTC+6)" },
  { value: "Asia/Novosibirsk",                 label: "Asia/Novosibirsk — Novosibirsk Time (NOVT, UTC+7)" },
  { value: "Asia/Rangoon",                     label: "Asia/Rangoon — Myanmar Time (MMT, UTC+6:30)" },
  { value: "Asia/Bangkok",                     label: "Asia/Bangkok — Indochina Time (ICT, UTC+7)" },
  { value: "Asia/Ho_Chi_Minh",                 label: "Asia/Ho_Chi_Minh — Indochina Time (ICT, UTC+7)" },
  { value: "Asia/Phnom_Penh",                  label: "Asia/Phnom_Penh — Indochina Time (ICT, UTC+7)" },
  { value: "Asia/Vientiane",                   label: "Asia/Vientiane — Indochina Time (ICT, UTC+7)" },
  { value: "Asia/Jakarta",                     label: "Asia/Jakarta — Western Indonesia Time (WIB, UTC+7)" },
  { value: "Asia/Krasnoyarsk",                 label: "Asia/Krasnoyarsk — Krasnoyarsk Time (KRAT, UTC+7)" },

  // Asia — East & Southeast
  { value: "Asia/Kuala_Lumpur",                label: "Asia/Kuala_Lumpur — Malaysia Time (MYT, UTC+8)" },
  { value: "Asia/Singapore",                   label: "Asia/Singapore — Singapore Time (SGT, UTC+8)" },
  { value: "Asia/Manila",                      label: "Asia/Manila — Philippine Standard Time (PST, UTC+8)" },
  { value: "Asia/Taipei",                      label: "Asia/Taipei — China Standard Time (CST, UTC+8)" },
  { value: "Asia/Hong_Kong",                   label: "Asia/Hong_Kong — Hong Kong Time (HKT, UTC+8)" },
  { value: "Asia/Macau",                       label: "Asia/Macau — China Standard Time (CST, UTC+8)" },
  { value: "Asia/Shanghai",                    label: "Asia/Shanghai — China Standard Time (CST, UTC+8)" },
  { value: "Asia/Ulaanbaatar",                 label: "Asia/Ulaanbaatar — Ulaanbaatar Time (ULAT, UTC+8)" },
  { value: "Asia/Makassar",                    label: "Asia/Makassar — Central Indonesia Time (WITA, UTC+8)" },
  { value: "Asia/Irkutsk",                     label: "Asia/Irkutsk — Irkutsk Time (IRKT, UTC+8)" },
  { value: "Asia/Brunei",                      label: "Asia/Brunei — Brunei Time (BNT, UTC+8)" },
  { value: "Asia/Seoul",                       label: "Asia/Seoul — Korea Standard Time (KST, UTC+9)" },
  { value: "Asia/Pyongyang",                   label: "Asia/Pyongyang — Korea Standard Time (UTC+9)" },
  { value: "Asia/Tokyo",                       label: "Asia/Tokyo — Japan Standard Time (JST, UTC+9)" },
  { value: "Asia/Jayapura",                    label: "Asia/Jayapura — Eastern Indonesia Time (WIT, UTC+9)" },
  { value: "Asia/Yakutsk",                     label: "Asia/Yakutsk — Yakutsk Time (YAKT, UTC+9)" },
  { value: "Asia/Vladivostok",                 label: "Asia/Vladivostok — Vladivostok Time (VLAT, UTC+10)" },
  { value: "Asia/Sakhalin",                    label: "Asia/Sakhalin — Sakhalin Time (SAKT, UTC+11)" },
  { value: "Asia/Magadan",                     label: "Asia/Magadan — Magadan Time (MAGT, UTC+11)" },
  { value: "Asia/Srednekolymsk",               label: "Asia/Srednekolymsk — Srednekolymsk Time (UTC+11)" },
  { value: "Asia/Kamchatka",                   label: "Asia/Kamchatka — Kamchatka Time (PETT, UTC+12)" },
  { value: "Asia/Anadyr",                      label: "Asia/Anadyr — Anadyr Time (ANAT, UTC+12)" },

  // Australia
  { value: "Australia/Perth",                  label: "Australia/Perth — Australian Western Standard Time (AWST, UTC+8)" },
  { value: "Australia/Eucla",                  label: "Australia/Eucla — Australian Central Western Time (UTC+8:45)" },
  { value: "Australia/Darwin",                 label: "Australia/Darwin — Australian Central Standard Time (ACST, UTC+9:30)" },
  { value: "Australia/Adelaide",               label: "Australia/Adelaide — Australian Central Time (ACST/ACDT)" },
  { value: "Australia/Brisbane",               label: "Australia/Brisbane — Australian Eastern Standard Time (AEST, UTC+10)" },
  { value: "Australia/Lindeman",               label: "Australia/Lindeman — Australian Eastern Standard Time (UTC+10)" },
  { value: "Australia/Sydney",                 label: "Australia/Sydney — Australian Eastern Time (AEST/AEDT)" },
  { value: "Australia/Melbourne",              label: "Australia/Melbourne — Australian Eastern Time (AEST/AEDT)" },
  { value: "Australia/Hobart",                 label: "Australia/Hobart — Australian Eastern Time (AEST/AEDT)" },
  { value: "Australia/Lord_Howe",              label: "Australia/Lord_Howe — Lord Howe Time (UTC+10:30/11)" },

  // Pacific
  { value: "Pacific/Guam",                     label: "Pacific/Guam — Chamorro Standard Time (ChST, UTC+10)" },
  { value: "Pacific/Saipan",                   label: "Pacific/Saipan — Chamorro Standard Time (ChST, UTC+10)" },
  { value: "Pacific/Port_Moresby",             label: "Pacific/Port_Moresby — Papua New Guinea Time (PGT, UTC+10)" },
  { value: "Pacific/Chuuk",                    label: "Pacific/Chuuk — Chuuk Time (UTC+10)" },
  { value: "Pacific/Pohnpei",                  label: "Pacific/Pohnpei — Pohnpei Time (UTC+11)" },
  { value: "Pacific/Guadalcanal",              label: "Pacific/Guadalcanal — Solomon Islands Time (SBT, UTC+11)" },
  { value: "Pacific/Noumea",                   label: "Pacific/Noumea — New Caledonia Time (NCT, UTC+11)" },
  { value: "Pacific/Norfolk",                  label: "Pacific/Norfolk — Norfolk Island Time (UTC+11/12)" },
  { value: "Pacific/Majuro",                   label: "Pacific/Majuro — Marshall Islands Time (MHT, UTC+12)" },
  { value: "Pacific/Auckland",                 label: "Pacific/Auckland — New Zealand Time (NZST/NZDT)" },
  { value: "Pacific/Fiji",                     label: "Pacific/Fiji — Fiji Time (FJT, UTC+12)" },
  { value: "Pacific/Chatham",                  label: "Pacific/Chatham — Chatham Time (UTC+12:45/13:45)" },
  { value: "Pacific/Tongatapu",                label: "Pacific/Tongatapu — Tonga Time (TOT, UTC+13)" },
  { value: "Pacific/Apia",                     label: "Pacific/Apia — Samoa Time (WST, UTC+13)" },
  { value: "Pacific/Fakaofo",                  label: "Pacific/Fakaofo — Tokelau Time (TKT, UTC+13)" },
  { value: "Pacific/Kiritimati",               label: "Pacific/Kiritimati — Line Islands Time (LINT, UTC+14)" },

  // Pacific — West of UTC (negative offset)
  { value: "Pacific/Tahiti",                   label: "Pacific/Tahiti — Tahiti Time (TAHT, UTC-10)" },
  { value: "Pacific/Marquesas",                label: "Pacific/Marquesas — Marquesas Time (MART, UTC-9:30)" },
  { value: "Pacific/Gambier",                  label: "Pacific/Gambier — Gambier Time (GAMT, UTC-9)" },
  { value: "Pacific/Pitcairn",                 label: "Pacific/Pitcairn — Pitcairn Time (PST, UTC-8)" },
  { value: "Pacific/Pago_Pago",                label: "Pacific/Pago_Pago — Samoa Standard Time (SST, UTC-11)" },
  { value: "Pacific/Niue",                     label: "Pacific/Niue — Niue Time (NUT, UTC-11)" },

  // Atlantic / Other
  { value: "Atlantic/Cape_Verde",              label: "Atlantic/Cape_Verde — Cape Verde Time (CVT, UTC-1)" },
  { value: "Atlantic/Stanley",                 label: "Atlantic/Stanley — Falkland Islands Time (FKST, UTC-3)" },
  { value: "Indian/Maldives",                  label: "Indian/Maldives — Maldives Time (MVT, UTC+5)" },
  { value: "Indian/Mauritius",                 label: "Indian/Mauritius — Mauritius Time (MUT, UTC+4)" },
  { value: "Indian/Reunion",                   label: "Indian/Reunion — Réunion Time (RET, UTC+4)" },
  { value: "Indian/Chagos",                    label: "Indian/Chagos — Indian Ocean Time (IOT, UTC+6)" },
  { value: "Indian/Cocos",                     label: "Indian/Cocos — Cocos Islands Time (CCT, UTC+6:30)" },
  { value: "Indian/Christmas",                 label: "Indian/Christmas — Christmas Island Time (CXT, UTC+7)" },
]
